#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                               100
#define ID_PNG_RH_ENABLE                        103
#define ID_PNG_RH_DISABLE                       104
#define ID_PNG_RHL_ENABLE                        103
#define ID_PNG_RHL_DISABLE                       104
#define ID_PNG_RL_ENABLE                        103
#define ID_PNG_RL_DISABLE                       104
#define ID_PNG_RSH_ENABLE                        103
#define ID_PNG_RSH_DISABLE                       104
#define ID_PNG_CHL_ENABLE                        103
#define ID_PNG_CHL_DISABLE                       104
#define ID_PNG_RSL_ENABLE                        103
#define ID_PNG_RSL_DISABLE                       104
#define ID_PNG_CAN_HIGH_VOLT_PLUS                 103
#define ID_PNG_CAN_HIGH_VOLT_MINUS                104
#define ID_PNG_CAN_LOW_VOLT_PLUS                 103
#define ID_PNG_CAN_LOW_VOLT_MINUS                104
#define IDC_PICTURE_RH                          1000
#define IDC_COMBOX_LAYOUT                       1001
#define IDC_PICTURE_RHL                         1002
#define IDC_PICTURE_RL                          1003
#define IDC_CHECKBOX_OSC_LISTEN_PORT            1004
#define IDC_PICTURE_RSH                         1005
#define IDC_CHECKBOX_RH                         1006
#define IDC_PICTURE_CHL                         1007
#define IDC_PICTURE_RSL                         1008
#define IDC_PICTURE_CAN_H_VOLT                  1011
#define IDC_SLIDER_RHL                          1015
#define IDD_ANALOG_DISTURBANCE                  2001
#define IDC_SLIDER_RH                           2004
#define IDC_EDIT_RH                             2005
#define IDC_SPIN_RH                             2006
#define IDC_EDIT_RHL                            2007
#define IDC_SPIN_RHL                            2008
#define IDC_SLIDER_RL                           2009
#define IDC_EDIT_RL                             2011
#define IDC_SPIN_RL                             2012
#define IDC_SLIDER_RSH                          2013
#define IDC_EDIT_RSH                            2014
#define IDC_SPIN_RSH                            2015
#define IDC_SLIDER_CHL                          2016
#define IDC_SPIN_CHL                            2020
#define IDC_EDIT_CHL                            2021
#define IDC_SLIDER_RSL                          2022
#define IDC_EDIT_RSL                            2023
#define IDC_SPIN_RSL                            2024
#define IDC_CHECKBOX_RHL                        2025
#define IDC_CHECKBOX_RL                         2026
#define IDC_CHECKBOX_RSH                        2027
#define IDC_CHECKBOX_CHL                        2028
#define IDC_CHECKBOX_RSL                        2029
#define IDC_CHECKBOX_CANH_DIS_VOLT              2032
#define IDC_CHECKBOX_CANL_DIS_VOLT              2033
#define IDC_CHECKBOX_CAN_BUS_TYPE               2034
#define IDC_PICTURE_CAN_L_VOLT                  2035
